Add a basic homepage for the tool at tools.wmflabs.org
everypolitician/prompter pull request #5
Opened 2017-08-21 16:03 UTC by mhl

This PR adds a basic homepage for https://tools.wmflabs.org/prompter/

Desktop view:

![homepage-bigger](https://user-images.githubusercontent.com/7907/29528079-9d0dcfce-8692-11e7-8726-fa4143f02503.png)

Mobile view:

![prompter-mobile](https://user-images.githubusercontent.com/7907/29528020-6964f60c-8692-11e7-9ea0-88e469cf24d4.png)

Fixes #4

2017-08-21 16:49 UTC, chrismytton approved these changes
Thanks @mhl, this is great! 👍 🚀

2017-08-21 16:50 UTC, chrismytton commented on views/homepage.erb
> +        <li><a href="https://github.com/everypolitician/prompter">everypoltiian/prompter</a>: the HTTP interface to the tool</li>
Ooh, just noticed a typo here after approving! "everypoltiian"

2017-08-21 16:51 UTC, chrismytton commented on views/homepage.erb
> +        <a href="https://meta.wikimedia.org/wiki/Grants:Project/mySociety/EveryPolitician">MedaWiki
Oh and another here, "MedaWiki", though I think in this context it should probably be "Wikimedia", the org, rather than "MediaWiki", the software :)

2017-08-21 16:52 UTC, chrismytton requested changes
Sorry to approve and then reject, but I noticed a couple of typos after hitting the approve button!

2017-08-21 18:30 UTC, mhl commented
Well spotted :) - I've fixed those things now.

2017-08-22 08:45 UTC, chrismytton approved these changes
Nice! 😸 👌

2017-08-23 10:06 UTC, merged